apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-jva-casenotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-jva-casenotes
  template:
    metadata:
      labels:
        app: api-jva-casenotes
    spec:
      containers:
      - name: api-jva-casenotes
        image: 550964964577.dkr.ecr.eu-west-1.amazonaws.com/k8slab-api-jva-casenotes:latest
        ports:
        - containerPort: 80
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ENV
            value: k8slab 

---

apiVersion: v1
kind: Service
metadata:
  name: api-jva-casenotes-svc
  labels:
    app: api-jva-casenotes
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: api-jva-casenotes
    
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: casenotes.api
spec:
  rules:
  - host: casenotes.api
    http:
      paths:
      - path: /
        backend:
          serviceName: api-jva-casenotes-svc
          servicePort: 80
    
---