kind: Deployment
metadata:
  name: api-jva-casenotes-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-jva-casenotes-svc
  template:
    metadata:
      labels:
        app: api-jva-casenotes-svc
    spec:
      containers:
      - name: api-jva-casenotes-svc
        image: 550964964577.dkr.ecr.eu-west-1.amazonaws.com/k8slab-api-jva-casenotes:latest
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: api-jva-casenotes-svc
  labels:
    app: api-jva-casenotes-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-jva-casenotes-svc
    
---